# Generated by Django 3.1.2 on 2020-11-10 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='featuredPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('featured_field', models.CharField(choices=[('ARTICLE', 'ARTICLE'), ('PHILOSOPHY', 'PHILOSOPHY'), ('FASHION', 'FASHION'), ('LIFESTYLE', 'LIFESTYLE'), ('NATURE', 'NATURE')], default=None, max_length=20)),
                ('featured_titile', models.CharField(max_length=10)),
                ('featured_text', models.TextField(max_length=300)),
                ('featured_image', models.ImageField(upload_to='featuredImage')),
            ],
        ),
    ]
