# Generated by Django 3.1.2 on 2020-11-10 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_field', models.CharField(choices=[('ARTICLE', 'ARTICLE'), ('PHILOSOPHY', 'PHILOSOPHY'), ('FASHION', 'FASHION'), ('LIFESTYLE', 'LIFESTYLE'), ('NATURE', 'NATURE'), ('TRAVEL', 'TRAVEL')], default=None, max_length=20)),
                ('blog_tittle', models.CharField(max_length=20)),
                ('blog_text', models.TextField(max_length=500)),
                ('blog_image', models.ImageField(upload_to='blogImage')),
            ],
        ),
        migrations.RenameField(
            model_name='featuredpost',
            old_name='featured_titile',
            new_name='featured_tittle',
        ),
        migrations.AlterField(
            model_name='featuredpost',
            name='featured_field',
            field=models.CharField(choices=[('ARTICLE', 'ARTICLE'), ('PHILOSOPHY', 'PHILOSOPHY'), ('FASHION', 'FASHION'), ('LIFESTYLE', 'LIFESTYLE'), ('NATURE', 'NATURE'), ('TRAVEL', 'TRAVEL')], default=None, max_length=20),
        ),
    ]
