# Generated by Django 3.1.2 on 2020-11-15 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_featuredpost_featured_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='featuredpost',
            name='featured_id',
        ),
    ]
