# Generated by Django 3.1.2 on 2020-11-15 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_remove_featuredpost_featured_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featuredpost',
            name='featured_tittle',
            field=models.CharField(max_length=100),
        ),
    ]
